### ISSUE TITLE
The code about MCIE block 

### ISSUE THREAD

**Issue by MEcoder27** [w2kun/RNW#3]
Sorry I can not find the code of your MCIE block.
Could you please tell me the location of it ? That will be helpful to my research.

**Comment by w2kun** [comment]
We embed the MCIE block in `pack_data()` function of `RobotCarSequence` and `nuScenesSequence` classes (in `datasets/robot_car.py` and `datasets/nuscenes.py`, respectively). You can access the processed image through key `("color_equ", frame_id, scale)`.
